version: '3.4'

services:
  accountservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  atmservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

