name: CI/CD Pipeline

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker images
      run: |
        VERSION=$(date +'%Y%m%d%H%M%S')
        echo "Using default version $VERSION"
        
        echo "$DOCKER_PASSWORD" | docker login
        
        docker-compose build -t 254chege/ezy-account-service:$VERSION ./AccountService
        docker-compose push 254chege/ezy-account-service:$VERSION

        docker-compose build -t 254chege/ezy-atm-service:$VERSION ./ATMService
        docker-compose push 254chege/ezy-atm-service:$VERSION

        docker-compose build -t 254chege/ezy-api-gateway:$VERSION ./APIGateway
        docker-compose push 254chege/ezy-api-gateway:$VERSION

        docker-compose build -t 254chege/ezy-auth-service:$VERSION ./AuthService
        docker-compose push 254chege/ezy-auth-service:$VERSION

        docker-compose build -t 254chege/ezy-frontend:$VERSION ./Frontend
        docker-compose push 254chege/ezy-frontend:$VERSION
