name: Deployment

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure SSH
      run: |
        mkdir -p $HOME/.ssh
        echo -e "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_INSTANCE_IP }} >> $HOME/.ssh/known_hosts
        chmod 644 $HOME/.ssh/known_hosts
    

    - name: Deploy to EC2
      run: |
        ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_SSH_USERNAME }}@${{ secrets.EC2_INSTANCE_IP }} 'bash -s' < ~/deploy.sh
